package interface_adapter.AirportDataRS;

import use_case.AirportDataRouteSearch.AirportDataRouteSearchInputBoundary;
import use_case.AirportDataRouteSearch.AirportDataRouteSearchInputData;

public class AirportDataRSController {
}
